### Example: Logical functions

Let's see how the perceptron learns by training it on a couple of logical functions, AND and OR. For two variables x! and x2, the AND function returns 1 if both are TRUE, or 0 otherwise; the OR function returns 1 if either varible is TRUE, or both. These functions can be expressed as simple lookup tables.

In [1]:
import numpy as np
import pandas as pd

In [34]:
AND = pd.DataFrame({
    'x1':(0,0,1,1),
    'x2':(0,1,0,1),
    'y':(0,0,0,1)
})
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

First we need to initialize weights to small, random values(both positive and negative)

In [35]:
w = np.random.randn(3)*1e-4

In [19]:
w

array([-5.77339783e-07,  2.70448240e-06,  5.28481344e-05])

Then, a simple activation function for calculating g(h):

In [36]:
g =  lambda inputs, weights: np.where(np.dot(inputs, weights)>0, 1, 0)

Finally, a training function the iterates the learning algorithm, returning the adapted weights

In [37]:
def train(inputs, targets, weights, eta, n_iterations):
    
    inputs = np.c_[inputs, -np.ones((len(inputs),1))]# adding bias
    
    for _ in range(n_iterations):
        activations = g(inputs, weights);
        print(activations)
        weights -= eta*np.dot(np.transpose(inputs), activations - targets)##eta is the learning rate
        print(weights)
    return (weights)

In [38]:
inputs = AND[['x1','x2']]
target = AND['y']

w = train(inputs, target, w, 0.05, 10)

[1 1 1 1]
[-0.04999119 -0.04992073  0.14998104]
[0 0 0 0]
[8.80644994e-06 7.92662251e-05 9.99810440e-02]
[0 0 0 0]
[0.05000881 0.05007927 0.04998104]
[0 1 1 1]
[8.80644994e-06 7.92662251e-05 1.49981044e-01]
[0 0 0 0]
[0.05000881 0.05007927 0.09998104]
[0 0 0 1]
[0.05000881 0.05007927 0.09998104]
[0 0 0 1]
[0.05000881 0.05007927 0.09998104]
[0 0 0 1]
[0.05000881 0.05007927 0.09998104]
[0 0 0 1]
[0.05000881 0.05007927 0.09998104]
[0 0 0 1]
[0.05000881 0.05007927 0.09998104]


In [39]:
w

array([0.05000881, 0.05007927, 0.09998104])

In [40]:
g(np.c_[inputs, -np.ones((len(inputs),1))],w)

array([0, 0, 0, 1])