In [1]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  Running setup.py install for tensorflow-gpu: started
  Running setup.py install for tensorflow-gpu: finished with status 'error'


  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lmbmo\AppData\Local\Temp\pip-install-od84r0v3\tensorflow-gpu_e46afad5e6244004960799992c11f8c8\setup.py", line 37, in <module>
          raise Exception(TF_REMOVAL_WARNING)
      Exception:
      
      The "tensorflow-gpu" package has been removed!
      
      Please install "tensorflow" instead.
      
      Other than the name, the two packages have been identical
      since TensorFlow 2.1, or roughly since Sep 2019. For more
      information, see: pypi.org/project/tensorflow-gpu
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  error: subprocess-e

In [2]:
import tensorflow as tf
print(tf.__version__)
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

2.11.0


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=500

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[82, 96, 290, 175], [82, 96, 290, 10], [82, 138, 290, 226], [494, 114, 238, 305, 419], [494, 114, 238, 305, 370], [457, 82, 64, 290, 249], [18, 270, 450, 305]]


### Word Embedding Representation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length = 0
for i in range(len(sent)):
    if len(sent[i].split()) > sent_length:
        sent_length = len(sent[i].split())
print(f'Maximum sentence length is {sent_length}')

Maximum sentence length is 5


In [8]:
#pre padding
sent_length=sent_length+3
# we increase the setn_length a little to not have out of vocab issue
embedded_docs=pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  82  96 290 175]
 [  0   0   0   0  82  96 290  10]
 [  0   0   0   0  82 138 290 226]
 [  0   0   0 494 114 238 305 419]
 [  0   0   0 494 114 238 305 370]
 [  0   0   0 457  82  64 290 249]
 [  0   0   0   0  18 270 450 305]]


In [9]:
# feature representation
dim=10
# 10 should be enough as we very small sentence

In [10]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
embedded_docs[0]

array([  0,   0,   0,   0,  82,  96, 290, 175])

In [11]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 147ms/step


array([[-0.0270307 ,  0.00797524, -0.02988589,  0.00375221,  0.00224423,
        -0.01572689, -0.00613006, -0.02783823,  0.02065761,  0.02721696],
       [-0.0270307 ,  0.00797524, -0.02988589,  0.00375221,  0.00224423,
        -0.01572689, -0.00613006, -0.02783823,  0.02065761,  0.02721696],
       [-0.0270307 ,  0.00797524, -0.02988589,  0.00375221,  0.00224423,
        -0.01572689, -0.00613006, -0.02783823,  0.02065761,  0.02721696],
       [-0.0270307 ,  0.00797524, -0.02988589,  0.00375221,  0.00224423,
        -0.01572689, -0.00613006, -0.02783823,  0.02065761,  0.02721696],
       [ 0.01124078,  0.01102644, -0.00688881,  0.01070916, -0.00382366,
        -0.01973114,  0.0359012 , -0.01637311, -0.03529534,  0.03832814],
       [ 0.010799  , -0.0460222 ,  0.01765305, -0.03532173,  0.02056715,
        -0.03962339,  0.01036368,  0.00660773,  0.01819089,  0.022079  ],
       [-0.03294869,  0.03080585, -0.03379887, -0.04127785, -0.00591446,
        -0.01255221,  0.04429166, -0.00319735

In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 76ms/step


array([[[-0.0270307 ,  0.00797524, -0.02988589,  0.00375221,
          0.00224423, -0.01572689, -0.00613006, -0.02783823,
          0.02065761,  0.02721696],
        [-0.0270307 ,  0.00797524, -0.02988589,  0.00375221,
          0.00224423, -0.01572689, -0.00613006, -0.02783823,
          0.02065761,  0.02721696],
        [-0.0270307 ,  0.00797524, -0.02988589,  0.00375221,
          0.00224423, -0.01572689, -0.00613006, -0.02783823,
          0.02065761,  0.02721696],
        [-0.0270307 ,  0.00797524, -0.02988589,  0.00375221,
          0.00224423, -0.01572689, -0.00613006, -0.02783823,
          0.02065761,  0.02721696],
        [ 0.01124078,  0.01102644, -0.00688881,  0.01070916,
         -0.00382366, -0.01973114,  0.0359012 , -0.01637311,
         -0.03529534,  0.03832814],
        [ 0.010799  , -0.0460222 ,  0.01765305, -0.03532173,
          0.02056715, -0.03962339,  0.01036368,  0.00660773,
          0.01819089,  0.022079  ],
        [-0.03294869,  0.03080585, -0.03379887, -0.0

In [14]:
### Assignment

sent=["The world is a better place",
      "Marvel movies are my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"]

In [15]:
### Vocabulary size
voc_size=500

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[82, 499, 384, 238, 415, 443], [49, 496, 450, 431, 423, 270], [494, 70, 345, 496], [82, 96, 384, 185, 82, 64], [91, 289, 493, 384, 431, 423, 270], [235, 384, 431, 423, 129, 427]]


In [17]:
sent_length = 0
for i in range(len(sent)):
    if len(sent[i].split()) > sent_length:
        sent_length = len(sent[i].split())
print(f'Maximum sentence length is {sent_length}')

Maximum sentence length is 7


In [18]:
## pre padding
sent_length=sent_length+3
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  82 499 384 238 415 443]
 [  0   0   0   0  49 496 450 431 423 270]
 [  0   0   0   0   0   0 494  70 345 496]
 [  0   0   0   0  82  96 384 185  82  64]
 [  0   0   0  91 289 493 384 431 423 270]
 [  0   0   0   0 235 384 431 423 129 427]]


In [19]:
## 10 feature dimesnions
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [22]:
##'The world is a better place',
embedded_docs[0]

array([  0,   0,   0,   0,  82, 499, 384, 238, 415, 443])

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 71ms/step


array([[ 0.00953779,  0.03549981,  0.04574737,  0.00833737,  0.02803966,
         0.03589184, -0.02499791,  0.04538051, -0.01218151,  0.04770775],
       [ 0.00953779,  0.03549981,  0.04574737,  0.00833737,  0.02803966,
         0.03589184, -0.02499791,  0.04538051, -0.01218151,  0.04770775],
       [ 0.00953779,  0.03549981,  0.04574737,  0.00833737,  0.02803966,
         0.03589184, -0.02499791,  0.04538051, -0.01218151,  0.04770775],
       [ 0.00953779,  0.03549981,  0.04574737,  0.00833737,  0.02803966,
         0.03589184, -0.02499791,  0.04538051, -0.01218151,  0.04770775],
       [ 0.02681348, -0.03508812,  0.04007054, -0.00280043,  0.0015764 ,
        -0.0448323 , -0.0357504 ,  0.03324788, -0.0113659 ,  0.02329982],
       [ 0.02205027,  0.02083863,  0.03310417, -0.04064215,  0.017458  ,
        -0.00155235, -0.03049693,  0.01933068,  0.04538289, -0.02658782],
       [-0.0442851 ,  0.0098606 ,  0.02468357, -0.02099853, -0.03649157,
         0.04909602,  0.04510445,  0.03730213

In [24]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 62ms/step
[[[ 0.00953779  0.03549981  0.04574737  0.00833737  0.02803966
    0.03589184 -0.02499791  0.04538051 -0.01218151  0.04770775]
  [ 0.00953779  0.03549981  0.04574737  0.00833737  0.02803966
    0.03589184 -0.02499791  0.04538051 -0.01218151  0.04770775]
  [ 0.00953779  0.03549981  0.04574737  0.00833737  0.02803966
    0.03589184 -0.02499791  0.04538051 -0.01218151  0.04770775]
  [ 0.00953779  0.03549981  0.04574737  0.00833737  0.02803966
    0.03589184 -0.02499791  0.04538051 -0.01218151  0.04770775]
  [ 0.02681348 -0.03508812  0.04007054 -0.00280043  0.0015764
   -0.0448323  -0.0357504   0.03324788 -0.0113659   0.02329982]
  [ 0.02205027  0.02083863  0.03310417 -0.04064215  0.017458
   -0.00155235 -0.03049693  0.01933068  0.04538289 -0.02658782]
  [-0.0442851   0.0098606   0.02468357 -0.02099853 -0.03649157
    0.04909602  0.04510445  0.03730213 -0.04349843  0.0327948 ]
  [ 0.00245811 -0.03489213  0.02522658 -0.03276129 -0.01239208