## 00. Pytorch fundamentals

Resources:
- https://www.learnpytorch.io/
- https://github.com/mrdbourke/pytorch-deep-learning


In [24]:
import torch
x = torch.rand(5,3)
print(x)

tensor([[0.0886, 0.3490, 0.7993],
        [0.1897, 0.7015, 0.3300],
        [0.3067, 0.2281, 0.4236],
        [0.4711, 0.5058, 0.8514],
        [0.2795, 0.1642, 0.4157]])


In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to tensors

Pytorch tensors are created using torch.Tensor()
Documentations here: https://pytorch.org/docs/stable/tensors.html




In [3]:
# Creating a tensor
scalar = torch.tensor(7)
scalar



tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#Creating a vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

matrix = torch.tensor([[7,8],
                       [9,10]])

In [10]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
# Tensor
Tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [4,7,6]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 7, 6]]])

In [15]:
Tensor.ndim

3

In [16]:
Tensor.shape

torch.Size([1, 3, 3])

The size indicates that we have a 1 3*3 matrix

In [17]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 7, 6]])

## Random tensors
Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensor full of random numbers to better understand the data.

- Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [18]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8416, 0.6152, 0.1621, 0.7210],
        [0.0598, 0.2767, 0.3955, 0.4888],
        [0.2252, 0.1631, 0.3512, 0.8448]])

In [19]:

random_tensor = torch.rand(4,4,4)
random_tensor

tensor([[[0.1750, 0.3346, 0.1327, 0.3286],
         [0.8285, 0.6079, 0.1108, 0.5852],
         [0.4499, 0.5194, 0.0372, 0.5099],
         [0.4404, 0.1056, 0.8287, 0.0796]],

        [[0.5996, 0.3308, 0.3156, 0.1634],
         [0.8356, 0.8219, 0.8505, 0.9373],
         [0.0837, 0.3694, 0.2715, 0.2463],
         [0.8773, 0.8357, 0.2419, 0.5588]],

        [[0.2186, 0.7124, 0.2302, 0.6421],
         [0.4617, 0.8384, 0.4049, 0.3487],
         [0.4325, 0.4870, 0.3534, 0.5705],
         [0.6012, 0.2033, 0.0823, 0.2740]],

        [[0.2572, 0.4455, 0.4074, 0.1000],
         [0.2202, 0.8549, 0.3485, 0.3486],
         [0.1173, 0.5885, 0.4442, 0.3563],
         [0.1300, 0.9038, 0.1402, 0.9519]]])

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor[1]

tensor([[0.5996, 0.3308, 0.3156, 0.1634],
        [0.8356, 0.8219, 0.8505, 0.9373],
        [0.0837, 0.3694, 0.2715, 0.2463],
        [0.8773, 0.8357, 0.2419, 0.5588]])

In [32]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width , color channels(R, G, B)

In [34]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with torch.zeros()

Again, the size parameter comes into play.


In [25]:
# Creating a tensor full of zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# The same can be done with ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range and tensor like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)


In [27]:
# use torch.arange(), torch.arange() is deprecated
zero_to_ten_deprecated = torch.range(0,10)

# Create a range of value 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-27-f6d80e267bcc>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [28]:

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

The reason for all of these is to do with **precision in computing.**

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).


In [29]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with dtype=torch.float16.

### Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)
Let's create a random tensor and find out details about it.

In [30]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.9144, 0.7639, 0.6002, 0.7267],
        [0.6129, 0.3969, 0.8582, 0.9410],
        [0.1771, 0.4827, 0.1411, 0.3652]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

Addition
Substraction
Multiplication (element-wise)
Division
Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

### Basic operations
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

They work just as you think they would.

In [31]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [35]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [36]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [37]:

# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [38]:

# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [39]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
- (3, 2) @ (3, 2) won't work
- (2, 3) @ (3, 2) will work
- (3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
- (2, 3) @ (3, 2) -> (2, 2)
- (3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation. [https://pytorch.org/docs/stable/generated/torch.matmul.html]

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

In [40]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

The difference between element-wise multiplication and matrix multiplication is the addition of values.

In [41]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [42]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [45]:
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)

%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.66 ms, sys: 0 ns, total: 1.66 ms
Wall time: 1.59 ms


tensor(14)

In [46]:

%%time
torch.matmul(tensor, tensor)

CPU times: user 109 µs, sys: 10 µs, total: 119 µs
Wall time: 125 µs


tensor(14)

### One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [47]:

# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

- torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
- tensor.T - where tensor is the desired tensor to transpose.
Let's try the latter.

In [48]:

# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [49]:

# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [50]:
# You can also use torch.mm() which is a short for torch.matmul().
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Neural networks are full of matrix multiplications and dot products.

The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.
      
      y = x.A^T + b

Where:

- x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
- A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).
  - Note: You might also often see W or another letter like X used to showcase the weights matrix.
- b is the bias term used to slightly offset the weights and inputs.
- y is the output (a manipulation of the input in the hopes to discover patterns in it).
This is a linear function (you may have seen something like $y = mx+b$
 in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features below` and see what happens.

Do you notice anything to do with the shapes?

In [53]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


> **Question:** What happens if you change `in_features` from 2 to 3 above? Does it error? How could you change the shape of the input (x) to accomodate to the error? Hint: what did we have to do to `tensor_B` above?


### Finding the min, max, mean, sum, etc (aggregation)
Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.

In [54]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [57]:
# You can also do the same as above with torch methods.

torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

## Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [58]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0
